---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgoat-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webgoat
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webgoat
    spec:
      containers:
        - image: deepfenceio/wg:1.1.1
          imagePullPolicy: Always
          name: webgoat
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 200Mi
              cpu: 200m
            limits:
              memory: 500Mi
              cpu: 500m
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - webgoat
              topologyKey: topology.kubernetes.io/zone
      restartPolicy: Always
      imagePullSecrets:
        - name: deepfence-docker-secret

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webgoat-service
  name: webgoat-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: "Local"
  selector:
    app: webgoat
  ports:
    - name: webgoat-service-port
      port: 80
      protocol: TCP
      targetPort: 8080
---
apiVersion:  apps/v1
kind: Deployment
metadata:
  name: skipfish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skipfish
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: skipfish
    spec:
      containers:
        - image: deepfenceio/skipfish:latest
          imagePullPolicy: Always
          name: skipfish
          command: ["/root/start.sh"]
          env:
            - name: "USER_PWD"
              value: "deepfence:deepfence"
            - name: "URL"
              value: "http://webgoat-service/WebGoat/login"
            - name: "NUM_TRIES"
              value: "500"
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - skipfish
              topologyKey: topology.kubernetes.io/zone
      restartPolicy: Always