---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admission-webhook
  name: admission-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-webhook
  template:
    metadata:
      labels:
        app: admission-webhook
    spec:
      containers:
        - name: webhook
          image: deepfenceio/admission-webhook:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8443
          env:
            - name: MGMT_CONSOLE_URL
              valueFrom:
                secretKeyRef:
                  name: admission-webhook-secret
                  key: MGMT_CONSOLE_URL
            - name: DEEPFENCE_KEY
              valueFrom:
                secretKeyRef:
                  name: admission-webhook-secret
                  key: DEEPFENCE_KEY
          volumeMounts:
            - name: tls
              mountPath: "/certs"
              readOnly: true
          resources:
            limits:
              memory: 256Mi
              cpu: 100m
      volumes:
        - name: tls
          secret:
            secretName: admission-webhook-tls
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: admission-webhook
  name: admission-webhook
spec:
  type: ClusterIP
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: admission-webhook